#!/bin/bash

brew install autoconf automake libtool pkg-config bison boost openssl@1.1
rm -rf lib/php/src/ext/thrift_protocol/build/
./bootstrap.sh
./configure \
      --disable-debug \
      --disable-tests \
      --without-erlang \
      --without-haskell \
      --without-java \
      --without-perl \
      --without-php \
      --without-php_extension \
      --without-python \
      --without-ruby \
      --without-swift
npm install -g npm-check-updates
npm-check-updates -u
npm install
npm audit fix
make
